/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;

CREATE TABLE `Testigo` (
  `DNI` int(11) NOT NULL,
  PRIMARY KEY (`DNI`),
  CONSTRAINT `FK_TestigoPersona` FOREIGN KEY (`DNI`) REFERENCES `Persona` (`DNI`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
